In [292]:
import pandas as pd
import numpy as np

In [293]:
df = pd.read_csv('heart.csv')
df.shape

(918, 12)

In [294]:
df.head(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [295]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [296]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [297]:
# def outliers_remove_using_z_score(dataframe, col):
#   z_score = (dataframe[col] - dataframe[col].mean()) / dataframe[col].std()
#   return dataframe[(z_score > -3) & (z_score < 3)]

In [298]:
# outliers_remove_using_z_score(df, 'Cholesterol').shape

In [299]:
def outliers_remove_using_z_score(dataframe, col):
  lower_limit = dataframe[col].mean()-3*dataframe[col].std()
  higher_limit = dataframe[col].mean()+3*dataframe[col].std()
  return dataframe[(dataframe[col] > lower_limit) & (dataframe[col] <= higher_limit)]

In [300]:
df1 = outliers_remove_using_z_score(df, 'Cholesterol')
df2 = outliers_remove_using_z_score(df1, 'RestingBP')
df3 = outliers_remove_using_z_score(df2, 'FastingBS')
df4 = outliers_remove_using_z_score(df3, 'MaxHR')
df5 = outliers_remove_using_z_score(df4, 'Oldpeak')

In [301]:
df5.shape

(899, 12)

In [302]:
df6 = pd.get_dummies(df5, drop_first=True, dtype=int)
df6.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [303]:
X = df6.drop('HeartDisease', axis='columns')
y = df6['HeartDisease']

In [304]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [305]:
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[-1.42815446,  0.46590022,  0.84963584, -0.5503622 ,  1.38431998,
        -0.85546862,  0.515943  ,  2.06332497, -0.5349047 , -0.22955001,
         0.80970176, -0.48989795, -0.8229452 , -0.99888827,  1.13469459],
       [-0.47585532,  1.63471366, -0.16812204, -0.5503622 ,  0.7529728 ,
         0.13751561, -1.93819859, -0.48465463,  1.86949191, -0.22955001,
         0.80970176, -0.48989795, -0.8229452 ,  1.00111297, -0.88129441],
       [-1.7455875 , -0.1185065 ,  0.79361247, -0.5503622 , -1.53566071,
        -0.85546862,  0.515943  ,  2.06332497, -0.5349047 , -0.22955001,
        -1.23502263,  2.04124145, -0.8229452 , -0.99888827,  1.13469459]])

In [306]:
y.value_counts()

HeartDisease
1    492
0    407
Name: count, dtype: int64

In [307]:
492/407

1.2088452088452089

In [308]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, test_size=0.2, random_state=42)

In [309]:
y_train.value_counts()

HeartDisease
1    393
0    326
Name: count, dtype: int64

In [310]:
393/326

1.205521472392638

In [311]:
from sklearn.svm import SVC
model = SVC().fit(X_train, y_train)

In [312]:
model.score(X_test, y_test)

0.8944444444444445

In [313]:
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier(
    estimator=SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)

BaggingClassifier(estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=0)

In [314]:
bag_model.oob_score_

0.8678720445062587

In [315]:
bag_model.score(X_test, y_test)

0.8888888888888888

In [316]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier().fit(X_train, y_train)

In [317]:
model2.score(X_test, y_test)

0.8111111111111111

In [318]:
bag_model2 = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
).fit(X_train, y_train)

In [319]:
bag_model2.score(X_test, y_test)

0.8555555555555555

In [320]:
bag_model2.oob_score_

0.8372739916550765

In [321]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier().fit(X_train, y_train)

In [322]:
model3.score(X_test, y_test)

0.8777777777777778