In [680]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [681]:
iris_data = load_iris()
df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
df['target'] = iris_data.target
df.sample(5)

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
8                  4.4               2.9  ...               0.2       0
7                  5.0               3.4  ...               0.2       0
68                 6.2               2.2  ...               1.5       1
103                6.3               2.9  ...               1.8       2
100                6.3               3.3  ...               2.5       2

[5 rows x 5 columns]

In [682]:
kf = KFold(n_splits=3)
for train_idx, test_idx in kf.split([1, 2, 3, 4, 5, 6, 7, 8], [0, 0, 0, 0, 1, 1, 1, 1]):
  print(train_idx, test_idx)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]

In [683]:
X = df.drop('target', axis=1)
Y = df.target

In [684]:
X[10:]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[140 rows x 4 columns]

In [685]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [686]:
folds = StratifiedKFold(n_splits=3)
for train_idx, test_idx in folds.split([1, 2, 3, 4, 5, 6, 7, 8], [0, 0, 0, 0, 1, 1, 1, 1]):
  print(train_idx, test_idx)

[2 3 5 6 7] [0 1 4]
[0 1 3 4 7] [2 5 6]
[0 1 2 4 5 6] [3 7]

In [687]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [688]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [689]:
score_l = []
score_dt = []
score_rf = []
score_svm = []

folds2 = StratifiedKFold(n_splits=3)
for train_idx, test_idx in folds2.split(X, Y):
  X_train, X_test, y_train, y_test = X.iloc[train_idx], X.iloc[test_idx], Y.iloc[train_idx], Y.iloc[test_idx]
  score_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
  score_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
  score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
  score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [690]:
score_l

[0.98, 0.96, 0.98]

In [691]:
score_dt

[0.98, 0.92, 1.0]

In [692]:
score_rf

[0.98, 0.94, 0.98]

In [693]:
score_svm

[0.96, 0.98, 0.94]

In [694]:
l_score = cross_val_score(LogisticRegression(max_iter=1000), X, Y, cv=3)
np.average(l_score)

np.float64(0.9733333333333333)

In [695]:
dt_score = cross_val_score(DecisionTreeClassifier(), X, Y, cv=3)
np.average(dt_score)

np.float64(0.96)

In [696]:
rf_score = cross_val_score(RandomForestClassifier(), X, Y, cv=3)
np.average(rf_score)

np.float64(0.96)

In [697]:
svm_score = cross_val_score(SVC(), X, Y, cv=3)
np.average(svm_score)

np.float64(0.96)