In [457]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [458]:
breast_cancer = load_breast_cancer()
df = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [459]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [460]:
x = df.copy()
y = breast_cancer.target

In [461]:
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [462]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [463]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [464]:
len(X_train)

455

In [465]:
len(X_test)

114

In [466]:
model = GaussianNB().fit(X_train, y_train)

In [467]:
model.score(X_test, y_test)

0.956140350877193

In [468]:
model.predict_proba(X_test)

array([[1.51750238e-002, 9.84824976e-001],
       [1.00000000e+000, 8.30180891e-022],
       [2.09665642e-014, 1.00000000e+000],
       [3.58673829e-011, 1.00000000e+000],
       [1.00000000e+000, 7.85512295e-070],
       [1.62277626e-011, 1.00000000e+000],
       [5.97441886e-005, 9.99940256e-001],
       [8.05030650e-005, 9.99919497e-001],
       [2.29604605e-012, 1.00000000e+000],
       [1.00000000e+000, 4.38940741e-083],
       [5.07169100e-004, 9.99492831e-001],
       [2.88517658e-011, 1.00000000e+000],
       [2.54162167e-015, 1.00000000e+000],
       [2.74562290e-010, 1.00000000e+000],
       [8.34996846e-012, 1.00000000e+000],
       [1.00000000e+000, 2.36556938e-075],
       [3.29272442e-002, 9.67072756e-001],
       [5.94737428e-014, 1.00000000e+000],
       [9.60144031e-014, 1.00000000e+000],
       [3.71871105e-018, 1.00000000e+000],
       [3.72184049e-017, 1.00000000e+000],
       [3.66525462e-015, 1.00000000e+000],
       [1.45375484e-011, 1.00000000e+000],
       [1.00000000e+000, 2.90808525e-019],
       [1.11456555e-012, 1.00000000e+000],
       [1.00000000e+000, 5.27445496e-102],
       [2.80819969e-016, 1.00000000e+000],
       [2.21854787e-012, 1.00000000e+000],
       [1.34592628e-013, 1.00000000e+000],
       [1.00000000e+000, 4.52367343e-013],
       [6.60332605e-010, 9.99999999e-001],
       [3.16660424e-012, 1.00000000e+000],
       [2.33029950e-015, 1.00000000e+000],
       [1.00000000e+000, 6.00891587e-030],
       [1.08331503e-017, 1.00000000e+000],
       [1.00000000e+000, 1.77067319e-099],
       [5.38055699e-015, 1.00000000e+000],
       [1.00000000e+000, 1.63634440e-052],
       [1.00000000e+000, 6.48730771e-033],
       [1.05543488e-012, 1.00000000e+000],
       [1.70582824e-003, 9.98294172e-001],
       [1.00000000e+000, 4.39092007e-016],
       [7.67776933e-001, 2.32223067e-001],
       [1.54477490e-013, 1.00000000e+000],
       [4.79399525e-013, 1.00000000e+000],
       [2.53091656e-012, 1.00000000e+000],
       [1.14959330e-009, 9.99999999e-001],
       [1.18992203e-007, 9.99999881e-001],
       [7.27316134e-005, 9.99927268e-001],
       [5.47876590e-011, 1.00000000e+000],
       [4.22706823e-013, 1.00000000e+000],
       [3.17795793e-016, 1.00000000e+000],
       [1.46292585e-010, 1.00000000e+000],
       [1.00000000e+000, 1.28655303e-012],
       [4.48219955e-011, 1.00000000e+000],
       [2.13545592e-013, 1.00000000e+000],
       [1.00000000e+000, 7.23796521e-055],
       [1.73803256e-014, 1.00000000e+000],
       [8.79206475e-012, 1.00000000e+000],
       [2.32677755e-011, 1.00000000e+000],
       [6.59973634e-014, 1.00000000e+000],
       [2.06135939e-015, 1.00000000e+000],
       [9.93807726e-001, 6.19227373e-003],
       [1.00000000e+000, 1.91755225e-010],
       [1.00000000e+000, 8.76048422e-054],
       [5.61362807e-008, 9.99999944e-001],
       [1.00000000e+000, 1.18512258e-047],
       [4.73737121e-016, 1.00000000e+000],
       [1.63067489e-004, 9.99836933e-001],
       [2.78346609e-016, 1.00000000e+000],
       [1.75956722e-013, 1.00000000e+000],
       [1.00000000e+000, 2.17380712e-025],
       [1.06164337e-015, 1.00000000e+000],
       [7.00511118e-016, 1.00000000e+000],
       [1.00000000e+000, 8.24356609e-014],
       [6.00361132e-015, 1.00000000e+000],
       [1.00000000e+000, 2.55056911e-228],
       [2.79376821e-011, 1.00000000e+000],
       [7.03476707e-016, 1.00000000e+000],
       [2.19976667e-010, 1.00000000e+000],
       [1.58351714e-015, 1.00000000e+000],
       [1.21418287e-016, 1.00000000e+000],
       [4.97310371e-015, 1.00000000e+000],
       [8.50187568e-018, 1.00000000e+000],
       [1.00000000e+000, 6.34906651e-088],
       [9.54098564e-006, 9.99990459e-001],
       [1.00000000e+000, 1.27506939e-029],
       [3.17791191e-015, 1.00000000e+000],
       [5.96116104e-014, 1.00000000e+000],
       [1.95752527e-015, 1.00000000e+000],
       [6.91293864e-002, 9.30870614e-001],
       [2.53905880e-011, 1.00000000e+000],
       [3.04058742e-002, 9.69594126e-001],
       [7.21446756e-001, 2.78553244e-001],
       [1.86126139e-016, 1.00000000e+000],
       [1.00000000e+000, 1.58444123e-096],
       [8.50462227e-010, 9.99999999e-001],
       [1.00000000e+000, 5.92549432e-112],
       [1.00000000e+000, 5.62952001e-022],
       [1.00000000e+000, 7.60810921e-079],
       [2.98688383e-014, 1.00000000e+000],
       [1.29866679e-014, 1.00000000e+000],
       [1.55568478e-014, 1.00000000e+000],
       [1.31662934e-015, 1.00000000e+000],
       [8.52152399e-010, 9.99999999e-001],
       [2.65137779e-012, 1.00000000e+000],
       [1.00000000e+000, 1.93156520e-043],
       [1.08384507e-011, 1.00000000e+000],
       [1.68643989e-015, 1.00000000e+000],
       [1.77101821e-015, 1.00000000e+000],
       [4.98662511e-017, 1.00000000e+000],
       [2.33607566e-013, 1.00000000e+000],
       [3.88204509e-016, 1.00000000e+000],
       [9.71528086e-001, 2.84719140e-002]])

Spam email prediction

In [469]:
df_spam = pd.read_csv('spam.csv')
df_spam

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [470]:
df_spam['spam'] = df_spam.Category.apply(lambda x: 1 if x == 'spam' else 0)
df_spam.sample(5)

     Category                                            Message  spam
2832      ham                         Thanx 4 sending me home...     0
1138      ham                           LOL ... No just was busy     0
4861      ham  Response is one of d powerful weapon 2 occupy ...     0
2053     spam  Call 09094100151 to use ur mins! Calls cast 10...     1
3042      ham            Aight what time you want me to come up?     0

In [471]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X = v.fit_transform(df_spam['Message'])
y = df_spam['spam']

In [472]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 74098 stored elements and shape (5572, 8709)>

In [473]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [474]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58751 stored elements and shape (4457, 8709)>

In [475]:
X_test.shape

(1115, 8709)

In [476]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB().fit(X_train, y_train)

In [477]:
model2.score(X_test, y_test)

0.9820627802690582

In [478]:
new_email = [
    "Congratulations! You have been selected for a $1000 Walmart gift card. Click here to claim now.",
    "URGENT: Your account has been suspended. Verify your details immediately.",
    "Limited time offer! Buy one get one free on all electronics.",
    "Win big prizes!!! Just reply YES to enter the lottery.",
    "You are the lucky winner of our free vacation package to Bahamas.",
    "Hey John, are we still on for dinner tomorrow?",
    "Please find the attached report for this week’s sales performance.",
    "Mom said she will be visiting us next weekend.",
    "Don’t forget to bring your laptop to the meeting.",
    "Let’s catch up over coffee sometime this week."
    ]
test_case = v.transform(new_email)
model2.predict(test_case)

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0])

In [479]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('model', MultinomialNB())
])

In [480]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(df_spam['Message'], df_spam['spam'], test_size=0.2)

In [481]:
clf.fit(X_train2, y_train2)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('model', MultinomialNB())])

In [482]:
clf.score(X_test2, y_test2)

0.9874439461883409

Exercise

In [483]:
from sklearn.datasets import load_wine
wines = load_wine()
dir(wines)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [484]:
df_wine = pd.DataFrame(wines.data, columns=wines.feature_names)
df_wine.head(5)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [485]:
df_wine.isna().any()

alcohol                         False
malic_acid                      False
ash                             False
alcalinity_of_ash               False
magnesium                       False
total_phenols                   False
flavanoids                      False
nonflavanoid_phenols            False
proanthocyanins                 False
color_intensity                 False
hue                             False
od280/od315_of_diluted_wines    False
proline                         False
dtype: bool

In [486]:
y = wines.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [487]:
X = df_wine.copy()

In [488]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.2, random_state=42)

In [489]:
model3 = GaussianNB().fit(X_train3, y_train3)
model4 = MultinomialNB().fit(X_train3, y_train3)

In [490]:
model3.score(X_test3, y_test3)

1.0

In [491]:
model4.score(X_test3, y_test3)

0.8888888888888888

In [492]:
from sklearn.model_selection import cross_val_score
gnb = cross_val_score(GaussianNB(), X, y)
mnb = cross_val_score(MultinomialNB(), X, y)

In [493]:
import numpy as np

In [494]:
np.average(gnb)

np.float64(0.9663492063492063)

In [495]:
np.average(mnb)

np.float64(0.843968253968254)