In [98]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [99]:
df = pd.read_csv('Melbourne_housing_FULL.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [100]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [101]:
useful_cols = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount',
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']

In [102]:
df2 = df[useful_cols]
df2.sample(5)

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
18386,Altona,4,h,SP,Barlow,Western Metropolitan,5301.0,11.0,Hobsons Bay City Council,4.0,2.0,2.0,629.0,180.0,935000.0
12230,Bentleigh,2,t,SP,McGrath,Southern Metropolitan,6795.0,13.0,Glen Eira City Council,2.0,2.0,1.0,0.0,NaN,620000.0
15060,Hoppers Crossing,3,h,S,hockingstuart,Western Metropolitan,13830.0,18.4,Wyndham City Council,NaN,NaN,NaN,NaN,NaN,460000.0
8835,Richmond,2,h,PI,Biggin,Northern Metropolitan,14949.0,2.6,Yarra City Council,2.0,1.0,1.0,67.0,NaN,NaN
3223,Clifton Hill,4,h,S,Collins,Northern Metropolitan,2954.0,3.4,Yarra City Council,4.0,3.0,2.0,382.0,250.0,3010000.0

In [103]:
df2.shape

(34857, 15)

In [104]:
df2.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [105]:
cols_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
df2[cols_fill_zero] = df2[cols_fill_zero].fillna(0)
df2.isna().sum()

/tmp/ipython-input-1294558875.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[cols_fill_zero] = df2[cols_fill_zero].fillna(0)

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        0
Distance             0
CouncilArea          3
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [106]:
df2['Landsize'] = df2['Landsize'].fillna(df2['Landsize'].mean())
df2['BuildingArea'] = df2['BuildingArea'].fillna(df2['BuildingArea'].mean())
df2.isna().sum()

/tmp/ipython-input-4163876355.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Landsize'] = df2['Landsize'].fillna(df2['Landsize'].mean())
/tmp/ipython-input-4163876355.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['BuildingArea'] = df2['BuildingArea'].fillna(df2['BuildingArea'].mean())

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [107]:
df2.dropna(inplace=True)

/tmp/ipython-input-1761232742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(inplace=True)

In [108]:
df2.isna().any()

Suburb           False
Rooms            False
Type             False
Method           False
SellerG          False
Regionname       False
Propertycount    False
Distance         False
CouncilArea      False
Bedroom2         False
Bathroom         False
Car              False
Landsize         False
BuildingArea     False
Price            False
dtype: bool

In [109]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27244 entries, 1 to 34856
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27244 non-null  object
 1   Rooms          27244 non-null  int64
 2   Type           27244 non-null  object
 3   Method         27244 non-null  object
 4   SellerG        27244 non-null  object
 5   Regionname     27244 non-null  object
 6   Propertycount  27244 non-null  float64
 7   Distance       27244 non-null  float64
 8   CouncilArea    27244 non-null  object
 9   Bedroom2       27244 non-null  float64
 10  Bathroom       27244 non-null  float64
 11  Car            27244 non-null  float64
 12  Landsize       27244 non-null  float64
 13  BuildingArea   27244 non-null  float64
 14  Price          27244 non-null  float64
dtypes: float64(8), int64(1), object(6)
memory usage: 3.3+ MB

In [110]:
df2.select_dtypes(include=['object']).columns

Index(['Suburb', 'Type', 'Method', 'SellerG', 'Regionname', 'CouncilArea'], dtype='object')

In [111]:
df2 = pd.get_dummies(df2, drop_first=True).astype(int)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27244 entries, 1 to 34856
Columns: 745 entries, Rooms to CouncilArea_Yarra Ranges Shire Council
dtypes: int64(745)
memory usage: 155.1 MB

In [112]:
X = df2.drop('Price', axis='columns')
y = df2.Price

In [113]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [114]:
model1 = LinearRegression().fit(X_train, y_train)
model2 = Lasso().fit(X_train, y_train)
model3 = Ridge().fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.266e+15, tolerance: 7.932e+11
  model = cd_fast.enet_coordinate_descent(

In [115]:
model1.score(X_train, y_train)

0.6814149524040823

In [116]:
model1.score(X_test, y_test)

0.66280777184951

In [117]:
model2.score(X_train, y_train)

0.6814000775281408

In [118]:
model2.score(X_test, y_test)

0.6632570384217181

In [119]:
model3.score(X_train, y_train)

0.6805178081072485

In [120]:
model3.score(X_test, y_test)

0.6683026479297969